config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
    resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w(chinese italian japanese french belgian)
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORY }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  validates :rating, inclusion: { in: RATING }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, label: 'Your username please', error: 'Username is mandatory, please specify one' %>
  <%= f.input :address, hint: 'No special characters.' %>
  <%= f.input :phone_number, placeholder: '00 33 1 45 65 89' %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div class="container">
  <h1 class="text-center">Tasks</h1>

  <ul class="row text-center">
    <% @restaurants.each do |restaurant|  %>
    <div class="col alert alert-primary text-center m-2 align-middle">
      <label for="completed" class="align-middle"><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></label>
    </div>
    <% end %>
  </ul>

  <div class="alert alert-success text-center m-2 align-middle">
    <%= link_to "Create new restaurant", new_restaurant_path %>
  </div>


</div>

app/views/restaurants/new.html.erb
<div class="container">
<h1>Create Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

</div>

app/views/restaurants/show.html.erb
<div class="container">

<h2><%= @restaurant.name %></h2>



<h2>Create Review</h2>


<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, label: 'Your review please', error: 'Please add your review' %>
  <%= f.input :rating, collection: Review::RATING %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

</div>